title: Nathan Truong # your name (or website title) here
logo: "/images/IMG_3047.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio!
  <br><br>
  I'm Nathan, a Data Graduate from the Australian Taxation Office (ATO). I hold a double degree in Actuarial Studies (Distinction) and Commerce from UNSW. Passionate about data science with proficiency in R, Python, SQL, and Power BI. I have practical experience in sales, data analysis, and making data-driven decisions. Explore my portfolio to see how I can contribute value to your team.
  <br><br>
  <a href="https://www.linkedin.com/in/n-truong/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: G-4JC6QJV6N6 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
