title: Nathan Truong # your name (or website title) here
logo: "/images/IMG_3047.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio!
  <br><br>
  I'm Nathan, a passionate Data Scientist at ITSM with over 2 years of industry experience. I'm currently pursuing a <strong>Masters of Data Science</strong> at the University of Sydney. 
  With a distinguished double degree in Actuarial Studies (Distinction) and Commerce from UNSW, I possess a strong foundation in data-driven decision-making. 
  My expertise spans across R, Python, SQL, and Power BI, allowing me to excel in statistical analysis, data analysis, and deploying machine learning/AI solutions.  
  Explore my portfolio to see how these skills and experiences can bring value to your team through innovative and analytical solutions.
  <br><br>
  <a href="https://www.linkedin.com/in/n-truong/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: G-4JC6QJV6N6 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
